### ISSUE TITLE
Error coming up during regular Writer use (non-admin)

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#774]
I'm working on screencasting Writer for partners and have gotten this error a few times in the last 15 minutes or so, to memory it came up when I first tried to log in (with a new account created for this purpose), when I tried to delete a draft (still worked but got the error page instead of landing back on the published articles page), and when I tried to save an article (see gif: http://g.recordit.co/pLQLh5fUfP.gif).

![screen shot 2016-07-15 at 10 06 01](https://cloud.githubusercontent.com/assets/10982707/16867772/0b98885a-4a74-11e6-8767-23cf3a6e315c.jpg)

**Comment by halleyjohnson** [comment]
Update: I'm also getting this error in my personal admin account—haven't gotten it in editorial account yet.

Just happening frequently when I try to perform a function like save, delete, unpublish

**Comment by halleyjohnson** [comment]
Copying error here:

Internal Server Error
Error: Internal Server Error
  at Request.callback (/app/node_modules/superagent/lib/node/index.js:698:17)
  at IncomingMessage.<anonymous> (/app/node_modules/superagent/lib/node/index.js:922:12)
  at emitNone (events.js:85:20)
  at IncomingMessage.emit (events.js:179:7)
  at IncomingMessage.wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:155:28)
  at IncomingMessage.wrappedEmit [as emit] (/app/node_modules/newrelic/lib/transaction/tracer/index.js:187:46)
  at endReadableNT (_stream_readable.js:913:12)
  at wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:155:28)
  at _combinedTickCallback (internal/process/next_tick.js:74:11)
  at process._tickCallback (internal/process/next_tick.js:98:9)

500
GET /api/articles?offset=0&limit=10&author_id=542b5e477261693a3d3d0200&published=false HTTP/1.1
Host: writer.artsy.net
x-newrelic-id: XAMFWFFTGwICVFhaAAcD
x-newrelic-transaction: PxQAWANWCQMJUVIHAQkEXkYdUFIOFQZOElUBBw0JBAsGVlxXCVILQEgUA1RVUlwCU1VDPw==
Accept-Encoding: gzip, deflate
User-Agent: node-superagent/1.8.3
x-access-token: JvTPWe4WsQO-xqX6Bts49misY7x1_LYPjr4VcrbCSmFp_INSYU9DXdkRkOQiPD9uDv25BhiB3DFUZS5LD1ssU_27_QVZKujvvJP_bZIJafl8fQsRvGjk4haJnhEdSCg2xwgsC28eZPrVUxVOOYn1l117yUM8Hij470uaBqMB8Cl-k80VOYIdcuroeEWSo7gT_JMuNU9TXt99uR2bNXxoF0cd9xf432dmz3Q5EZ6uQU_tabR6obxKbuVj7f1b_IigW9uXiqmZMO04iLxGDqYp2ljkE5PslDTuGwHqyixXA0D4JDGQKVD9-5tf_PXCDCucNT4Fx6UFjgW31lOpt9Kisg==
Connection: close

{"status":500,"message":"no primary server available"}
